name: Deploy to Cloudflare Pages

on:
  # Trigger on push to main branch when client files change
  push:
    branches:
      - main
      - master
    paths:
      - "client/**"
  
  # Allow manual triggering from GitHub Actions UI
  workflow_dispatch:

# Add explicit permissions needed for deployments
permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: ./client
        run: npm install
        env:
          NODE_ENV: development

      - name: Build Vite app
        working-directory: ./client
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ vars.SUPABASE_ANON_KEY }}
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ vars.STRIPE_PUBLISHABLE_KEY }}
          VITE_STRIPE_PRICE_ID: ${{ vars.STRIPE_PRICE_ID }}
          NODE_ENV: production

      - name: Upload to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          projectName: ${{ vars.CF_PROJECT_NAME }}
          directory: client/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
