name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'supabase/functions/**'
      - 'supabase/config.toml'
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Deploy Edge Functions to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
        run: |
          # Install Supabase CLI locally
          npm install supabase
          
          # Link to the Supabase project
          npx supabase link --project-ref $SUPABASE_PROJECT_ID
          
          # Deploy all Edge Functions
          npx supabase functions deploy
          
          echo "✅ Successfully deployed Supabase Edge Functions"
