name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to get all migrations

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Deploy migrations to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          # Install Supabase CLI locally
          npm install supabase

          # Use npx to run Supabase commands
          npx supabase link --project-ref $SUPABASE_PROJECT_ID

          # Use --include-all flag to ensure all migrations are applied, even those that would be inserted before existing ones
          npx supabase db push --include-all
